project:
  type: website

website:
  title: "Sahil Patidar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: /blogs/
        text: Blog
      - href: /projects/
        text: Projects
      - href: /assets/My-Resume.pdf
        text: Resume
  favicon: /assets/images/favicon.ico
  open-graph:
    locale: en_IN
  cookie-consent: true
  # google-analytics:

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
